### ISSUE TITLE
Complaint on name collision

### ISSUE THREAD

**Issue by SOF3** [TheDiamondYT1/PocketFactions#2]
@LegendOfMCPE has developed a plugin of the same name several years ago:
https://github.com/LegendOfMCPE/PocketFactions

Although development is almost dead, as one of the earliest faction plugins, it still has its public value. Considering that this TheDiamondYT1/PocketFactions has not been widely used yet (so far the same number of stargazers :D), I request you to rename this plugin to avoid confusion.

**Comment by TheDiamondYT1** [comment]
**Ugh**

Its got more stargazers, actually. I also couldnt think of a good name for this plugin so i just added "Pocket" in front of it. I was aware of LegendOfMcpe/PocketFactions when creating this as well. 

> Although development is almost dead
You mean is dead.
