### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XDqrkneZ** [TheDiamondYT1/PocketFactions#7]
04:03:34 [INFO] Enabling PocketFactions v0.0.1
04:03:34 [CRITICAL] ErrorException: "Illegal offset type" (EXCEPTION) in "/plugins/PocketFactions-master/src/TheDiamondYT/PocketFactions/provider/JSONProvider" at line 42
04:03:34 [INFO] Disabling PocketFactions v0.0.1

**Comment by TheDiamondYT1** [comment]
I'm currently rewriting it.
